// GENERATED by scripts/byteaudit-seal.mjs. Do not edit by hand.
//
// Each line is the SHA-256 of one sealed ByteAudit file. If you are reading this
// in a diff, the backstop that decides whether a note may be filed has changed —
// that is what this file exists to make impossible to miss. Check that the change
// beside it is one you meant.

import type { SealManifest } from "./seal";

export const SEAL: SealManifest = {
  version: "2026-08-05",
  files: {
  "contract.ts": "b54c53d9a44ac904e342fec434eab2cd4fe899772cafd82044704a09d6e9659f",
  "seal.ts": "4f533118c3557bf51cadc6e44331a790c6492af57ba9a6cd474bc7a91eb505fe",
  "verify.ts": "153c7f1207c2fd3682a9c41443ab9fbfb0a6064228ac8d063d129fdf78ba9191"
  }
};
