// Regenerate the ByteAudit seal. THE ONLY DOOR.
//
// Run by hand, on purpose:
//
//   node scripts/byteaudit-seal.mjs
//
// It rewrites src/lib/byteaudit/SEAL.ts with a hash of every sealed file, and
// that rewritten file must be committed in the SAME change as whatever moved.
// The resulting diff is one line per changed file, which is the point: a
// reviewer cannot miss that the backstop moved, because moving it is never a
// side effect of anything else.
//
// Nothing in the application calls this. It is not wired into build, dev, test,
// postinstall, or any hook, and it must never be — a seal the app can refresh on
// its own is a seal that records whatever the app currently is, which is no seal
// at all. If you find yourself adding this to a script that runs automatically,
// the thing you actually want is to revert the change that broke it.

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SEALED_DIR = path.resolve(HERE, "../src/lib/byteaudit");
const MANIFEST = path.join(SEALED_DIR, "SEAL.ts");

/** The manifest cannot hash itself, and tests are evidence rather than logic. */
const EXCLUDED = new Set(["SEAL.ts"]);

function sealedFiles(dir, prefix = "") {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...sealedFiles(path.join(dir, entry.name), rel));
    } else if (entry.name.endsWith(".ts") && !EXCLUDED.has(rel) && !rel.endsWith(".test.ts")) {
      out.push(rel);
    }
  }
  return out;
}

function hash(file) {
  // Bytes, not text. Normalising line endings here would let a change that only
  // alters them slip through, and on a file that decides whether a clinical
  // record may be filed, "only whitespace" is still not a change anyone should
  // be able to make invisibly.
  return createHash("sha256").update(readFileSync(path.join(SEALED_DIR, file))).digest("hex");
}

const files = sealedFiles(SEALED_DIR);
const entries = files.map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(hash(f))}`);

writeFileSync(
  MANIFEST,
  `// GENERATED by scripts/byteaudit-seal.mjs. Do not edit by hand.
//
// Each line is the SHA-256 of one sealed ByteAudit file. If you are reading this
// in a diff, the backstop that decides whether a note may be filed has changed —
// that is what this file exists to make impossible to miss. Check that the change
// beside it is one you meant.

import type { SealManifest } from "./seal";

export const SEAL: SealManifest = {
  version: ${JSON.stringify(new Date().toISOString().slice(0, 10))},
  files: {
${entries.join(",\n")}
  }
};
`
);

console.log(`Sealed ${files.length} file(s):`);
for (const f of files) console.log(`  ${f}`);
console.log(`\nWrote ${path.relative(process.cwd(), MANIFEST)}.`);
console.log("Commit it in the same change as whatever moved.");
