// GENERATED FILE — do not edit by hand.
// Rebuilt from skill/ markdown by scripts/build-lexicon.mjs.

const WORDS = `
aae aao aaoinfo aaomr aaoms aap aapd abandonment abbreviation abbreviations abc able
abnormality abo about above absent abstract abstracts abuse abutment accept accepted access
accessible accompanying accuracy accurate achieved acp acquired acquisition across act action actions
activation active actor acts actual actually acute ada adaclaimform adaj adams adapt
add addenda addendum addition additional addressed adds adequate adhesive adjacent adjunct adjustment
adjustments administer administered administering administers administration administrative administrator adopted adult adverse advertised
advertising advice after against age agent agents agonists agree ahrq aid aim
airway aligner aligners all allergies allergy allowing allowlist allowlisted alone also alter
altered altering alternatives alveolar ambiguity ambiguous amended americanboardortho among amount amounts analgesia
analgesic analytics analyze anatomic anatomical anatomy and anesthesia anesthetic angle angulation ann
annotated annual another answer answered anterior antianxiety antisepsis any api apical app
appears appliance appliances applicability applicable application applies apply appropriate approval approved arch
are areas arrangement arrest article articles artifact artifacts asa ask asks aspiration
assessable assessed assessment asset assets assign assigned assigns assistant assistants assisted associated
association attachment attachments attempted attestation attestations audio audit august authentication author authoritative
authorities authority authorization authorize authorized authorship auto automatically auxiliaries auxiliary available avoid
baa back backdate backup bands barriers base based baseline basis beam because
become before behavior behavioral below benchmark benefit benefits between billing biohazard biologic
biological biopsy bite bitewing blank blanks bleeding block blocked blocking blood bloodborne
board body bonding bone bones books border boundary braces bracket brackets breakage
breathing bridge broad broader browser buccal build buildup business but bwx calculate
calculation calculus call calling came can canal canals cancer candidacy cannot capability
capacity carbon cardiovascular care caregiver caries cartridges case catalog category causing cautions
cbct cdc cdt cement cementation central centrally cephalometric cephalometrics certification certified certify
chain change changed changes changing channel chapter chapters character characterization chart charted
charting chatgpt check checked checker checklist checklists checks chest chief child children
choice choose circulation cited claim claims clarity class classification classify cleaning cleanup
clearance click clinic clinical clinically clinician closure closures code codes coding cognition
collapse color column com combination commercial common communicated communication comorbidity compact comparable
compare compared compares comparison compilation compiled complete completed completeness completion completioninstructions complexity
compliance compliant complication complications component components comprehensive computed conceal concentration concentrations concept
concepts concern concise conclusion concurrent condition conditional conditions conduct cone conferencing confidence
confidentiality configure confirm confirmation confirmed confirms conflict conflicting congenitally conscious consciousness consensus
consent consented consequence consequences considered consistency consistent constantly consult consultation contact contacts
contain container containment contains content contents context continual continuity continuous contour contradict
contradiction contradictions contraindication control controlled controls conventional conversation convert converted coordination copies
copy copying copyrighted core coronal coronectomy correct corrected correction corrections correctness cost
could counsel counseling count counts course courses cover coverage covers cpe cranial
cre create creates creating creation credential credentials criteria criterion cross crown culture
curettage curing current custody cycle daily dam dash data database date dated
dates day days death debond debridement decide decision decisions declaration declined decortication
deep deeper default defaults defect deferred defibrillation deficiencies define defined defines definition
definitive delayed delegated delegation delivered delivery den denies density dental dentist dentistry
dentists dentition dentoalveolar dentrix denture departure deployment deposits depth describe described description
descriptors design designation designations designator destination destroy destruction detail detailed details determination
determine deterministic develop developers development developmental deviation deviations device devices diagnose diagnosed
diagnoses diagnosis diagnostic diagnostics did diet differential digital digitized dignity dimension dimensional
dimensions dioxide direct directed direction directions directly discharge discharged discipline disclosure discoloration
discontinued discovery discrepancy discussed discussion disease diseases disinfectants disinfection dispensed displacement disposal
disposition dispute disputed dissection distal distinction distinguish distraction distress distributed docs document
documentation documented documents does doi domain domains donor dose doses draft drafting
drain drainage draping dressing drivers drug drugs dry due duplicate duration during
duty dysphagia dyspnea each ear ebl edentulous edit edition edr education effect
effective effectiveness ehr eighteen either elapsed elastics elective electrocardiogram electrocardiography electronic element
elevation email emergencies emergency emitting empty emptying encounter end ended endodontic endodontics
endpoint enduring enough ensure enter enteral entered entire entries entry environment environmental
epa equipment era error errors eruption escalate escalation escort essential establish esthetic
esthetics estimated etc evaluation evenly event events every evidence evident exact exactly
exam examination examinations examined examples except exception exceptions excisional excursion exhaustive existing
exists expected expects experience expert expire expired explained explicit explicitly exposure express
extended extensible extent external extraction extraoral extremity extrusion eye fabricate face facebow
facial facilities facility facing fact factor factors facts failed failure false fastest
fasting fax fda features federal fee fees fever field fields fifth file
files fillable final finalization finalize find finding findings finish first fit fitness
five fix fixation fixative fixed fixing flag flagging flap flow fluorescence fluoride
fms fmx focused follow followed following for forcing foreign form formal format
formed forms formulation forward fracture fragment fragments framework free freedom freeze fremitus
from full function furcation fused future gas gases gastric gate gates general
generally generate generic genetic gingival gingivectomy give given gives globalassets gloss glp
glycemic goal goals google gov governance governing government governs grade graft grafting
grossly group growth guarantee guardian guardianship guidance guide guided guideline guidelines guides
hand handling handoff handoffs harbor hard hardcode harmonization harmonize harvest has have
having headache healing health healthy heart heat height help hemostasis hepatic hhs
hide hierarchy high hipaa historian history hold horizontal hospital hospitalization hosted how
hsps htm html https hub hygiene hygienist hygienists hyperthermia hyphen idea identifiable
identification identified identifier identifiers identify identifying identities identity image images imaging imitate
immediate immobilization impaction impairs implant implants implementation imply impression improve inadequate incapacity
incident incidental incisal incision incisional include included includes including incompetent incomplete inconsistent
incorrect indefinitely independent index indicated indication individual infection infer inference inflammation info
information infraction inhalation inherently initiating initiation injuries injury inlay input insertion inside
inspect inspection inspired installed instead institutional instruction instructions instrument instrumentation instruments intact
intake intended interaction interdisciplinary interest interference interoperability interpretation interpretations interpreted interpreter interpretive
interproximal interval intervals intervention interventions into intracanal intramuscular intranasal intraoperative intraoral intravenous
invalid invent involved ionizing ipr irrigants irrigation isolation issue issues item items
its ivs jada january jaw jebdp jmir join joint joints journal journals
judgment judgmental july jurisdiction keep known label labeled labels labial laboratory language
large laser last late later lateral laterality law lawful lawfully laws leaders
learn least leave ledge ledger left legal legislative length lengthening lesion lesions
let letter level levels levitin liability library license licensed licensees licensing licensure
ligament light lighting likely limit limitation limitations limited limits liner lingual link
linkage linked links list listed lists literacy load local locally located location
locations lock locked log logging logs longer loss lot lower lymph magnetic
mail maintain maintainer maintenance majority make making malignant management mandatory mandibular manual
manuals manufacturer map march margin margins mark markdown markers mass match matches
material materially materials matrix matters maxillary maxillofacial may meaning means measure measurement
measurements measures mechanics mechanism media medical medicament medication medications medicine medinform medium
meet member members membrane memory mental merely merge mergedprojects mesial messaging met
metadata method metrics micrograms midline milligrams milliliters minimal minimum minor minors misleading
missed missing mix mixed mixture mobility mod modality model models moderate modular
module modules moisture molar mold molding monitor monitoring monitoringsedation morbidity more motion
mouth move mucogingival mucosal multidetector multifactor multiplanar multiple muscle must nad naloxone
name named names narrative narrow nasal national natural nausea ncbi necessary neck
need needed needs negative negatives nerve nerves neurologic neurosensory never new newer
next nih nitrous nka nkda nlm node non nonclinical noncompliant none nonhospital
nonstandard normal normalization normalize normalizing not notation note notes notices notify now
nuclear number numbers objective objectives observation observations observed obtain obtained obturation obvious
occlusal occlusion october offer office official often ohi older omissions omitted oms
once one onlay only onset open openai opendental operating operation operational operative
opinion opioid opportunity opposing optical option optional options oral order ordered ordering
ordinarily ordinary org organization organizations orientation oriented original orofacial orthodontic orthodontics orthodontists
orthognathic osha osteotomy other otherwise out outcome outcomes outdated outpatient output outside
over overall overbite overdenture overjet overlap overlay overwrite owner ownership oxide oximetry
oxygen oxygenation pack packaged padding page pages pain pair paired pairing palatal
palliative palpation pano panoramic paper papers parameters parcar parcare parent parenteral part
partial participants participation partly parts pass passes passive past paste pathogen pathology
patient patients pattern pause payer pdf pediatric pediatrics peer people per percent
percentage percussion perforation perform performed performs peri periapical perio period periodic periodontal
periodontics periodontitis permanent permission permit permits permitted person personal personnel pertinent pet
pharmaceutical pharmaceuticals phi phonetics photograph photographs php phrase phrases physical physiologic pick
pii pilot pivotal placeholder placeholders placement plain plan planing planned planning plaque
platform plus pmc pmcid pmid pocket poi point pointers policies policy pontic
poor portal position positioning positive possible post posterior posteroanterior postoperative potential practice
practices preassessment precautions precise precision precluded prefilled pregnancy preinjury preliminary premedication premises
preoperative preparation preprocedure prescribed prescriber prescribing prescription prescriptions presedation presence present preservation
preserve preserved preserves preserving preset pressure prevented prevention preventive previews previous previously
primary principles prior priorities prioritized privacy private privilege prn pro probing problem
procedural procedure procedurenotes procedures proceed process processing processor produce product productfiles products
professional professionals profile prognosis program programs progress prohibited prohibits project projection projects
prompt prompts pronouns proof proper properly prophy prophylaxis proposes proprietary prosthesis prosthetic
prosthodontic prosthodontics protected protection protective protects protocol protocols provide provided provider provides
provision provisional provisions proximal proximity public publications publish published pubmed pulp pulpal
pulpectomy pulpotomy pulse purpose put quadrant qualified qualifying quality quantity queried question
questions quote quotes radiation radiograph radiographic radiographs radiography radiologist radiology range rate
rather raw ray rays rct reach reaches reaction reactions readable readiness reading
ready reaffirmation reaffirmed real reason reasonably reassess reassessment rebase recall received receives
receiving receptor recession recheck recipient recommend recommendation recommendations recommended reconcile reconciled reconciliation
record recorded recordings records recovery red reduction reevaluation reference references referral referrals
referred referrer refills refusal refuse refused regeneration regimen region registered registration regression
regulated regulates reinforcement related relation relative release released relevant reliability relief reline
rely remain remained remains reminder remote removable removal remove removed renal repair
repaired repeat replace replaces replantation replay report reported reporting reports repositioning repositories
representative representatives reproduce reproduced request requested requests require required requirement requirements requires
requiring rerun rescue research residual residue resolve resolved resonance resource resources respectively
respiratory response responses responsibility responsible responsiveness restorability restoration restorations restorative restraint restrictive
result results resuscitation retain retained retainer retainers retention retirement retraction retreatment retrieved
return reusable reuse reversal review reviewed reviewer revision right rights risk risks
role roles rollback rollout root route router routes routine routing rule rules
run runtime safe safeguarding safety sale salivary same satisfactory satisfy saturation say
scale scaling scan scavenging scheduled schedules scholar scholarly schools science scope score
screen screening screens screw sdf seal sealant sealer searched searches second secretary
section sectioning sections secure security sedating sedation sedationrecord sedative see seeking select
selected selection selectively self semantic send sensibility sensitive sentence sentences separate separately
separates separation september sequence serial series server service services set sets settings
seven severity sextant shade shall shaping shared sharps short shorthand show shows
side sign signature signatures signed significant signs silently similarity simple single sinus
site sites six size skeletal skill skills skin slash sleep small smallest
smart smoothing snodent snomed soap socket soft sore source sources space spaced
spaces sparse special specialist specialties specialty specific specified specimen spect speech spell
splint spot spotter spotting spread square srp stability stabilization stable staff staffing
stage stages stain stainless stale standard standardize standardized standards start started state
stated statement statements states status statute statutes statutory stay steel step steps
sterilization sterilizer sterilizers still stimulation stop stopped stopping storage store strategy stricter
strictest structure structured structures studies study style subject subjective subjects submentovertex submission
subprocessor substance substances substitute succession such suction suggest suitable summary supernumerary supervised
supervisee supervising supervision supplemental supplied supply support supported supporting suppuration surface surfaces
surgeon surgeries surgery surgical surveillance suture sutures swelling symptom symptoms synthetic system
systemic table target targeted task tbd teach teaching team technical technically technique
techniques technology teeth teledentistry telephone tell temperature template templates temporary temporomandibular ten
tenn tennessee tense term terminologies terminology terms test tested testing tests tetanus
text than that the their them therapeutic therapy there these they third
thirteen thirty this those three through throughout tickets tidal time times timing
tissue title tmd tmj tnsosfiles tobacco toc today todo tokede tolerated tomography
toolkit tools tooth topic topics torque total totals traces tracking train trained
training transcranial transfer transformations transillumination translation transmission transmitted transpharyngeal transport transportation trauma
traumatic treat treated treatment tried trigger triggered triggering triggers trismus true try
tuberosity turn two type types typo typos ultrasonography unannotated unauthorized unavailable uncertainty
unchanged unclear uncommon uncovering under underscores understanding unerupted unexpected unit units universal
unknown unless unlisted unpaid unprofessional unrelated unremarkable unresolved unsafe until unusual update
updated upload uploaded uploads urgency urgent urls use used useful user users
using vague valid validate validation value values variation vary vendor veneer ventilation
verbal vercel verification verified verifies verify version versioned versions vertical video view
violations visible visit vital voice volume vomiting voxel warning warnings warns was
waste waveform way weaken wear wedge weight well were what when where
whether which whichever while who whom why will wire with withhold within
without witness wizard wnl word wording words workflow working workspace wound wounds
write writing written wrong www year years yes yet younger your
`;

export const GENERATED_LEXICON: ReadonlySet<string> = new Set(
  WORDS.split(/\s+/).filter(Boolean)
);
