// GENERATED FILE — do not edit by hand.
// Rebuilt from skill/ markdown by scripts/build-lexicon.mjs.

const WORDS = `
aae aao aaoinfo aaomr aaoms aap aapd abandonment abbreviated abbreviation abbreviations abc
ability able abnormality abo about above abscess absent abstract abstracts abuse abuser
abutment accept accepted access accessible accompanying accuracy accurate accurately acetaminophen achieved acknowledgment
acp acquired acquisition across act action actions activation active actively actor acts
actual actually acute ada adaclaimform adaj adams adapt add added addenda addendum
addict adding addition additional addressed adds adequate adhesive adjacent adjunct adjustment adjustments
administer administered administering administers administration administrative administrator adopted adult adverse advertised advertising
advice advised aetiology affected afford after again against age agent agents aggravating
agonists agree agreed ahrq aid aim airway alert alerts aligner aligners all
allergies allergy allowing allowlist allowlisted alone along already also alter altered altering
alternative alternatives alveolar always ambiguity ambiguous amended americanboardortho among amount amounts analgesia
analgesic analysis analytics analyze anatomic anatomical anatomy and anesthesia anesthetic angle angulation
ann annotated annual another answer answered ant anterior antianxiety antibiotic antisepsis any
anything apap api apical apnea app appear appears appliance appliances applicability applicable
application applies apply appointment appointments appropriate approval approved arch are area areas
argument arranged arrangement arrest article artifact artifacts asa ask asked asks aspiration
assessable assessed assessment asset assets assign assigned assigns assist assistant assistants assisted
associated association asymptomatic attachment attachments attempted attend attendance attestation attestations attester attributing
audience audio audit audited august authentication author authoritative authorities authority authorization authorize
authorized authorship auto automated automatically autosave auxiliaries auxiliary available avoid baa back
backdate backup backups bad bands bandwidth bare barriers base based baseline basis
beam because become becomes becoming bedtime been before behavior behavioral behaviour being
belong belongs below benchmark benefit benefits beside better between beyond bid bilateral
billed billing biohazard biologic biological biopsy birth bite bitewing biw blank blanks
bleaching bleeding block blocked blocking blood bloodborne board body bonding bone bones
booking books border both bottom bounce boundary bounds braces bracket bracketed brackets
break breakage breathing bridge broad broader browser buccal build buildup built but
button bwx cal calculate calculation calculus call calling came can canal canals
cancelled cancer candidacy cannot capability capacity capture carbon cardiovascular care caregiver caries
carried carries carry cartridges case cases catalog catches category caught cause causing
cautions cavity cbct cdc cdt cement cementation centimeters central century cephalometric cephalometrics
certification certified certify chain chair chairs chairside change changed changes changing channel
chapter chapters character characteristic characterization chart charted charting charts chat check checked
checker checklist checklists checkout checks chest chief child children chip choice choke
choose choosing circulation cited claim claims clarity class classification classified classify clean
cleaning cleanup clear clearance clearinghouse clearly clears clenching click clicking clinic clinical
clinically clinician close closes closure closures code codes coding cognition collapse colleague
collecting collection color colour column com combination combined comfort comfortable commence commercial
commission common communicated communication communications comorbidity compact companion comparable compare compared compares
comparison compilation compiled complains complaint complete completed completeness completion completioninstructions complex complexity
compliance compliant complication complications component components comprehensive computed conceal concentration concentrations concept
concepts concern concise conclusion concurrent condition conditional conditions conduct cone conferencing confidence
confidentiality configure confirm confirmation confirmed confirms conflict conflicting congenitally connected conscious consciousness
consensus consent consented consequence consequences considered consistency consistent consistently constantly consult consultation
consumes contact contacts contain container containment contains contaminated contamination content contents context
continual continuing continuity continuous contour contouring contradict contradiction contradictions contraindicated contraindication contributing
control controlled controls conventional conversation convert converted coordination copied copies copy copying
copyrighted core coronal coronectomy corporate correct corrected correction corrections correctly correctness cosmetic
cost could counsel counseling count counts course courses cover coverage covers cpe
cranial crash cre create creates creating creation credential credentials crepitus criteria criterion
critical cross crown cubic culture cures curettage curing curiosity current custody custom
cuts cycle cycles daily dam dash dashboard dashboards data database date dated
dates day days death debond debridement decay decide decided decision decisions declaration
declined decortication deep deeper deepest default defaults defect deferred defibrillation deficiencies define
defined defines definition definitive deflection delayed delegated delegation deliberately deliver delivered delivery
den denies density dental dentist dentistry dentists dentition dentoalveolar dentrix denture department
departure depend dependencies dependency depends deployment deposit deposits depth derived describe described
description descriptors design designated designation designations designator desk destination destroy destruction detail
detailed details determination determine deterministic develop development developmental deviation deviations device devices
diabetes diabetic diagnose diagnosed diagnoses diagnosis diagnostic diagnostics dialog dictionary did died
diet differ different differential difficult digital digitized dignity dimension dimensional dimensions dioxide
dip direct directed direction directions directly discharge discharged discipline disclosure discoloration discontinue
discontinued discovery discrepancy discussed discussion disease diseases disinfectants disinfection disorder disorders dispensed
displacement disposal disposition dispute disputed disruptive dissection distal distinct distinction distinguish distraction
distress distributed docs doctors document documentation documented documents does doi domain domains
donor dose doses double doubt downstream draft drafting drain drainage draping dressing
drive drivers drives dropdown dropdowns drug drugs dry due duplicate duration during
duty dysphagia dyspnea each ear ebl edema edentulous edit editing edition edr
education effect effective effectiveness effects efficacy efficiently effort ehr eighteen either elapsed
elastics elective electrocardiogram electrocardiography electronic element elevation eliminates eliminating else email emailed
emerge emergencies emergency emitting empty emptying enabled enables encounter end ended endo
endocarditis endodontic endodontics endodontist endpoint enduring enforce enforced engine engineering english enough
ensure enter enteral entered entire entirely entries entry environment environmental epa epi
epilepsy epileptic epinephrine epworth equipment era error errors eruption erythema escalate escalation
escort essential establish estate esthetic esthetics estimate estimated etc etiology evaluated evaluation
even evenly event events ever every everyone everything evidence evident exacerbate exact
exactly exam examination examinations examined examples except exception exceptions excisional excursion exhaustion
exhaustive existing exists expand expectations expected expects expensive experience expert expire expired
explained explaining explicit explicitly export exposure express extended extensible extent external extraction
extraoral extremity extrusion exudate eye fabricate face facebow facial facilities facility facing
fact factor factors facts fail failed failure false familiarity faster fasting fault
fax fda features federal fee feel feels fees fever fewer field fields
fifth figures file filed files fillable filling filter filtering filters final finalization
finalize find finding findings fingers finish finished first fit fitness five fix
fixation fixative fixed fixing flag flagged flagging flags flap flight floor floors
flow fluid fluorescence fluoride flyer fms fmx focused follow followed following follows
for forces forcing foreign form formal format formats formatting formed forms formulation
forward four fracture fragment fragments framework free freedom fremitus frequent friction from
front full fully function furcation fused future gain gap gaps gas gases
gastric gate gateway gauntlet gave general generally generate generation generic genetic get
gingival gingivectomy gingivitis give given gives globalassets gloss glp glycemic goal goals
google gov governance governing government governs grade graft grafting granular greatest green
grinding grossly group growth guarantee guardian guardianship guidance guide guided guideline guidelines
gum gumline gums half hand handling handoff handoffs happen happened harbor hard
hardcode harmonization harmonize harvest has have haven having headache header headers healing
health healthy heart heat height help hemostasis hepatic here heuristic heuristically hhs
hide hiding hierarchy high hipaa historian historical histories history hold holding holds
home honest honestly horizontal hospital hospitalization hosted hosting hours how hsps htm
html https hub huddle human hygiene hygienist hygienists hyperthermia hyphen idea identifiable
identification identified identifier identifiers identify identifying identities identity ignored iii image images
imaging imitate immediate immediately immobilization imp impact impaction impairs implant implants implementation
imply impression improve inadequate incapacity incident incidental incisal incision incisional include included
includes including incompetent incomplete inconsistent incorrect indefinitely independent index indexed indicated indication
individual infection infer inference inflammation info information infraction infrastructure inhalation inherently initials
initiate initiating initiation injuries injury inlay input insertion inside inspect inspection inspired
instead institute institutional instruction instructions instrument instrumentation instruments insufficient intact intake integration
integrity intended interaction interdisciplinary interest interesting interference internal international interoperability interpretation interpretations
interpreted interpreter interpretive interproximal interval intervals intervention interventions into intracanal intramuscular intranasal
intraoperative intraoral intravenous invalid invent inventing invisible involved involvement ionizing ipr irrigants
irrigation iso isolation issue issues item items its itself ivs jada january
jaw jebdp jmir join joined joint joints journal journals jrb judge judged
judgment judgmental july jurisdiction just keep keeping keeps key know knowledge known
lab label labeled labels labial laboratory labs language large largely larger laser
last late later lateral laterality law lawful lawfully laws layer lazy lead
leaders leads least leave ledge ledger left legal legislative length lengthening lesion
lesions less let letter level levels levitin liability library license licensed licensees
licensing licensure lido lidocaine ligament light lighting like likely limit limitation limitations
limited limits line liner lines lingual link linkage linkages linked links list
listed lists literacy live lives load local localized locally located location locations
lock locked locking log logged logging logs long longer loss lot lower
lymph made magnesium magnetic mail mailbox maintain maintainer maintaining maintenance majority make
makes making malignant management manager managers mandatory mandible mandibular manual manuals manufacturer
map mapped march margin margins mark markdown marked markers masked masking mass
match matches material materially materials matrix matters maxilla maxillary maxillofacial maximum may
meaning means measurable measure measured measurement measurements measures mechanics mechanism media medical
medicament medication medications medicine medinform medium meet member members membrane mental mention
merely merge mergedprojects mesial message messages messaging met metadata method mgso micrograms
midline might migrating migration milligrams milliliters minimal minimum minor minors misleading misread
missed missing mistake mix mixed mixture mobility mock mod modality model models
moderate modern modified modify modular module modules moisture molar mold molding moment
monitor monitoring monitoringsedation monthly months morbidity more morning morphine motion mouth move
mso mucogingival mucosal multi multidetector multifactor multiplanar multiple muscle must nad naloxone
name named names narrative narrow nasal national natural nausea ncbi necessary necessity
neck necrosis necrotic need needed needs negative negatives negotiable nerve nerves neurologic
neurosensory never new newer next nice nih nitrous nka nkda nlm node
noise non noncompliant none nonhospital nonstandard normal normalization normalize normalizing normally not
notation note notes nothing noticed notices notification notify now nuclear number numbers
numbing objective objectives observation observations observed obstructive obtain obtained obturation obvious occlusal
occlusion october oedema offer offered office official often ohi older omissions omitted
oms once one ones ongoing onlay only onset open opendental opening operating
operation operational operative operatories opinion opioid opportunity opposing opposite optical option optional
options oral order ordered ordering ordinarily ordinary org organization organizations orientation oriented
original orofacial orphaned orthodontic orthodontics orthodontists orthognathic osha osteotomy other otherwise our
out outcome outcomes outdated outpatient output outside outweighs over overall overbite overdenture
overdose overjet overlap overlay override overriding overwrite overwrites own owner ownership owns
oxide oximetry oxygen oxygenation pack package packaged padding page pages pain pair
paired pairing palatal palliative palpate palpated palpation pano panoramic paper papers parafunction
paragraph parameters parcar parcare parent parenteral parse part partial participants participation partly
parts pass passes passive past paste pasted patch pathogen pathology patient patients
pattern pause payer pdf pediatric pediatrics peer people per perc percent percentage
percocet percussion perforation perform performed performs peri periapical perio period periodic periodontal
periodontics periodontitis permanent permission permissions permit permits permitted person personal personnel pertinent
pet pharmaceutical pharmaceuticals phases phasing phi phone phonetics photograph photographs php phrase
phrases physical physician physiologic pick pii pivotal place placeholder placeholders placement plain
plainer plan planing planned planning plans plaque platform plus pmc pmcid pmid
pocket poi point pointers points policies policy polysomnography pontic poor portal position
positioning positive possible post posterior posteroanterior postoperative potential potentially powers practice practices
pre preassessment precautions precise precision precluded preference prefilled pregnancy preinjury preliminary preload
premedication premises preoperative preparation preprocedure prerequisites prescribed prescriber prescribing prescription prescriptions presedation
presence present presenting preservation preserve preserved preserves preserving preset pressing pressure prevent
prevented prevention preventive previews previous previously primary principles prior priorities prioritized privacy
privilege prn pro probing problem procedural procedure procedurenotes procedures proceed process processing
processor produce produced product productfiles production productive productivity products professional professionals profile
prognosis program programs progress prohibited prohibits project projection prompt prompts prone pronouns
proper properly prophy prophylaxis proposed proposes proprietary prose prosthesis prosthetic prosthodontic prosthodontics
protected protecting protection protective protects protocol protocols protrusion protrusive proven provide provided
provider provides provision provisional provisions proximal proximity public publications publish published pubmed
pulp pulpal pulpectomy pulpitis pulpotomy pulse purpose pus put qhs quadrant qualified
qualifying quality quantified quantity queried question questions quiet quote quotes radiation radiograph
radiographic radiographs radiography radiologist radiology raises random range rate rather raw ray
rays rct reach reached reaches reaction reactions read readable reader readiness reading
reads ready reaffirmation reaffirmed real reason reasonably reasons reassess reassessed reassessment rebase
recall recalls received receives receiving receptor recession recheck recipient recognised recommend recommendation
recommendations recommended reconcile reconciled reconciliation record recorded recordings records recovered recovery red
redness reduced reducing reduction reevaluation reference references referral referrals referred referrer referring
refills refusal refuse refused regeneration regimen region registered registration regression regulated regulates
regulatory reinforcement reject rejected related relation relative release relevant reliability reliable reliably
relief relieving reline rely relying remain remained remains remediation reminder reminders remote
removable removal remove removed removing renal renamed render repair repaired repeat repeated
repeats replace replacement replaces replantation replay replies report reported reporting reports repositioning
repositories repository representative representatives reproduce reproduced request requested requests require required requirement
requirements requires requiring rerun rescue research resend residual residue resisted resolve resolved
resonance resource resources respectively respiratory response responses responsibility responsible responsiveness restate restatement
restorability restoration restorations restorative restores restoring restraint restrictive result results resuscitation retain
retained retainer retainers retention retirement retraction retraining retreatment retrieve retrieved return reusable
reuse reversal review reviewed reviewer revised revision reward rework rewrites rewritten right
rights rigorous ripple risk risks roi role roles rollback rollout root route
router routes routine routing rule ruled rules run runs runtime safe safeguarding
safety said sale salivary same satisfactory satisfies satisfy saturation save saved saves
say says scale scaling scan scattering scavenging scheduled schedules scheduling schema scholar
scholarly schools science sclerosis scope score screen screening screens screw sdf seal
sealant sealer search searched searches second secretary section sectioning sections secure security
sedating sedation sedationrecord sedative see seeking seizure select selected selection selectively self
semantic send sensibility sensitive sensitivity sentence sentences separate separately separates separation september
sequelae sequence sequences sequential serial series server servers service services set sets
settings seven severity sextant shade shall shaping shared sharps short shorthand should
show shows side sides sign signal signals signature signatures signed significant signs
silently similarity simple simply single sinus sit site sites six size skeletal
skill skin skipped slash sleep sleepiness slowdown small smallest smart smile smooth
smoothing snodent snomed snoring soap socket soft solve someday something sore source
sources space spaced spaces sparse special specialist specialties specialty specific specified specimen
spect speech spell splint spot spotter spotting spread square srp stability stabilization
stable staff staffing stage stages stain stainless stakes stale standard standardize standardized
standards start started state stated statement statements states stating status statute statutes
statutory stay stays steel step steps sterile sterilization sterilizer sterilizers still stimulation
stitches stockouts stop stopped stopping stops storage store stored storing strategy strength
strengthen stricter strictest string stronger structural structure structured structures studies study style
styled subject subjective subjects submentovertex submission submissions submits subprocessor subsequent substance substances
substitute succession such suction suggest suitable sulfate summary supernumerary supervised supervisee supervising
supervision supervisors supplemental supplied supplies supply support supported supporting suppuration surface surfaces
surfacing surgeon surgeries surgery surgical surveillance survived suture sutures swelling swollen symptom
symptoms synthetic system systemic systems tab table tables take taken taking tapping
target targeted tartar task tbd teach teaching team tech technical technically technique
techniques technology teeth teledentistry telephone tell tells temp temperature template templates temporary
temporomandibular ten tenn tennessee tense term terminologies terminology terms test tested testing
tests tetanus text than that the their them then therapeutic therapy there
these they third thirteen thirty this those threading threads three through throughout
ticket tickets tidal time times timing tissue title titration tiw tmd tmj
tnsosfiles tobacco toc today todo tokede token tokens tol tolerated tomography too
tool toolkit tools tooth toothpaste topic topics torque total totals touches toward
traces tracking train trained training transcranial transcribed transfer transformations transillumination transition translation
transmission transmitted transpharyngeal transport transportation trauma traumatic travel treat treated treatment trial
tried trigger triggered triggering triggers trismus true try tuberosity turn turning tweak
twice two type typed types typing typo typos ultrasonography unannotated unassisted unauthorized
unavailable uncertainty unchanged unclear uncommon uncooperative uncovering undeniable under underlying underscores understand
understanding undo unerupted unexpected unilateral unique unit units universal unknown unless unlisted
unpaid unprofessional unreadable unrelated unremarkable unresolved unsafe until unusual update updated upload
uploaded uploads upper urgency urgent urls use used useful user users using
usually utilize vague valid validate validation value values variation vary vendor veneer
ventilation verbal verbatim vercel verdict verification verified verifies verify version versioned versus
vertical vessels video view views violations visible visit vital vocabulary voice volume
vomiting voxel waiver walks wanted wants warning warnings warns was waste waveform
way weaken wear web wedge week weight well were what when where
whether which whichever while white whitening who whoever whole whom whose why
will wire with withhold within without witness wnl word wording words workaround
workflow working works workup worse worst would wound wounds write writing written
wrong www year years yes yet you younger your zero
`;

export const GENERATED_LEXICON: ReadonlySet<string> = new Set(
  WORDS.split(/\s+/).filter(Boolean)
);
