// Curated high-confidence dental/medical misspellings. Keys lowercase.
//
// Safe-edit boundary: a medication-name typo is never a style fix. The audit
// keeps it at S2 REVIEW until a clinician verifies the source record.

export const MEDICATION_WORDS: ReadonlySet<string> = new Set([
  "acetaminophen",
  "amoxicillin",
  "articaine",
  "aspirin",
  "azithromycin",
  "benzocaine",
  "bupivacaine",
  "chlorhexidine",
  "clindamycin",
  "codeine",
  "dexamethasone",
  "diazepam",
  "epinephrine",
  "fentanyl",
  "flumazenil",
  "fluoride",
  "hydrocodone",
  "hydroxyzine",
  "ibuprofen",
  "ketamine",
  "lidocaine",
  "mepivacaine",
  "metronidazole",
  "midazolam",
  "naloxone",
  "naproxen",
  "oxycodone",
  "penicillin",
  "prednisone",
  "prilocaine",
  "propofol",
  "tramadol",
  "triazolam"
]);

export const MISSPELLINGS: Record<string, string> = {
  abcess: "abscess",
  absess: "abscess",
  abcessed: "abscessed",
  acetaminophin: "acetaminophen",
  aveolitis: "alveolitis",
  alveoler: "alveolar",
  amalgum: "amalgam",
  amalgalm: "amalgam",
  amoxicilin: "amoxicillin",
  amoxycillin: "amoxicillin",
  anaesthesia: "anesthesia",
  anasthesia: "anesthesia",
  anesthisia: "anesthesia",
  anethesia: "anesthesia",
  anelgesic: "analgesic",
  antibotic: "antibiotic",
  articane: "articaine",
  asprin: "aspirin",
  benzocane: "benzocaine",
  brusxism: "bruxism",
  bruxsim: "bruxism",
  bucal: "buccal",
  buccle: "buccal",
  calculas: "calculus",
  capnograpy: "capnography",
  clindamyacin: "clindamycin",
  currettage: "curettage",
  debridment: "debridement",
  diazapam: "diazepam",
  edentuous: "edentulous",
  epinephrin: "epinephrine",
  extration: "extraction",
  fentanil: "fentanyl",
  fentynol: "fentanyl",
  flouride: "fluoride",
  fluroide: "fluoride",
  gingavitis: "gingivitis",
  gingervitis: "gingivitis",
  gingeva: "gingiva",
  hemorage: "hemorrhage",
  hemorrage: "hemorrhage",
  hemmorhage: "hemorrhage",
  ibuprofin: "ibuprofen",
  ibuprophen: "ibuprofen",
  inflamation: "inflammation",
  infammation: "inflammation",
  lidocane: "lidocaine",
  lignocaine: "lidocaine",
  linguel: "lingual",
  maxilary: "maxillary",
  medazolam: "midazolam",
  messial: "mesial",
  nitrus: "nitrous",
  oclusal: "occlusal",
  occlusial: "occlusal",
  osseus: "osseous",
  oxymetry: "oximetry",
  panaramic: "panoramic",
  penicilin: "penicillin",
  pericornitis: "pericoronitis",
  periodontel: "periodontal",
  periodontol: "periodontal",
  perodontal: "periodontal",
  perscription: "prescription",
  precussion: "percussion",
  proceedure: "procedure",
  prophalaxis: "prophylaxis",
  prophylaxsis: "prophylaxis",
  radigraph: "radiograph",
  sealent: "sealant",
  swolen: "swollen",
  temperomandibular: "temporomandibular",
  tempromandibular: "temporomandibular",
  xerostoma: "xerostomia"
};
